### ISSUE TITLE
pdf版本在Kindle上不能正确显示封面,字号稍小了些,

### ISSUE THREAD

**Issue by Yasin27878** [hltj/kotlin-web-site-cn#1]
pdf做的很精美,目录也很到位 唯一可惜的是在kindle上封面不能正常显示,不美观(可能我有点强迫症吧) 另一个就是整个文档的字号小了点  可以稍微调大点,便于在移动设备上更清晰的看. 谢谢

**Comment by hltj** [comment]
在 Kindle 上看建议考虑 GitBook 上的版本：https://www.gitbook.com/book/hltj/kotlin-reference-chinese/details 上有下载链接。

PDF：https://www.gitbook.com/download/pdf/book/hltj/kotlin-reference-chinese
ePub：https://www.gitbook.com/download/epub/book/hltj/kotlin-reference-chinese
Mobi：https://www.gitbook.com/download/epub/book/hltj/kotlin-reference-chinese

**Comment by Yasin27878** [comment]
thanks




发自网易邮箱大师


在2017年05月19日 11:45，hltj<notifications@github.com> 写道：

在 Kindle 上看建议考虑 GitBook 上的版本：https://www.gitbook.com/book/hltj/kotlin-reference-chinese/details 上有下载链接。

PDF：https://www.gitbook.com/download/pdf/book/hltj/kotlin-reference-chinese
ePub：https://www.gitbook.com/download/epub/book/hltj/kotlin-reference-chinese
Mobi：https://www.gitbook.com/download/epub/book/hltj/kotlin-reference-chinese
