### ISSUE TITLE
关于防止翻译撞车的一些提议

### ISSUE THREAD

**Issue by Yue-plus** [hltj/kotlin-web-site-cn#178]
在开始翻译前先看下 PR，确认没有其他人在翻译。
在翻译时，先把文章标题翻译好并立即发一个 PR，格式类似：
`[翻译中……] 语言指南 - 集合 -  集合排序`
然后每翻译好一部分就推送一次。
当翻译完成一整篇，或翻译了一部分不想翻译了将 PR 的标题改为：
`[翻译完毕！] 语言指南 - 集合 -  集合排序`
或
`[请求合并！] 语言指南 - 集合 -  集合排序`
并且超过 28 小时没有推新 commit 的`[翻译中…]`将被关闭。

**Comment by HoshinoTented** [comment]
我觉得搞个 Gitter 也来讨论也不错（？）

**Comment by hltj** [comment]
> 我觉得搞个 Gitter 也来讨论也不错（？）

done:

[![Gitter](https://badges.gitter.im/kotlin-web-site-cn/community.svg)](https://gitter.im/kotlin-web-site-cn/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
