### ISSUE TITLE
链接失效(官网也是)

### ISSUE THREAD

**Issue by cnLGMing** [hltj/kotlin-web-site-cn#20]
[编译时长：Kotlin 支持高效的增量编译，所以对于清理构建会有额外的开销，增量构建通常与 Java 一样快或者更快。](https://www.kotlincn.net/docs/reference/android-overview.html)

**_增量构建通常与 Java 一样快或者更快_**  的链接失效([官网](http://kotlinlang.org/docs/reference/android-overview.html)也是)

**Comment by XuToTo** [comment]
链接并未失效，请尝试使用代理进行访问。

**Comment by cnLGMing** [comment]
抱歉...
我 SS 用 PAC 模式打不开...刚刚换成全局模式就可以了...
