### ISSUE TITLE
考虑一下把教程内 IDEA 的相关操作翻译成中文的？

### ISSUE THREAD

**Issue by Yue-plus** [hltj/kotlin-web-site-cn#216]
IDEA 有官方中文包了~

**Comment by hltj** [comment]
> IDEA 有官方中文包了~

最好等中文包正式发布之后吧，或者双语对照？

**Comment by Yue-plus** [comment]
> > IDEA 有官方中文包了~
> 
> 最好等中文包正式发布之后吧，或者双语对照？

我觉得最好能双语对照吧

**Comment by hltj** [comment]
> > > IDEA 有官方中文包了~
> > 
> > 
> > 最好等中文包正式发布之后吧，或者双语对照？
> 
> 我觉得最好能双语对照吧

那还是双语对照吧，就不用等正式发布了
