### ISSUE TITLE
安利一个好用的浏览器划词翻译插件~

### ISSUE THREAD

**Issue by Yue-plus** [hltj/kotlin-web-site-cn#223]
# [Saladict 沙拉查词](https://saladict.crimx.com/)

![QQ截图20200619115407](https://user-images.githubusercontent.com/33195150/85095411-ebed0500-b223-11ea-9c11-85bd4e3079b7.png)
![QQ截图20200619115445](https://user-images.githubusercontent.com/33195150/85095415-ed1e3200-b223-11ea-8c78-7f1ad84c7f1d.png)

**Comment by imknown** [comment]
分享一个 我平时用的 词典列表:

---

- `CNKI翻译助手`: 列出了 各个意思 的比重, 方便 术语翻译
- `有道词典`: 可以看 词汇等级 (CET4 之类) 和 使用频率, 顺便可以 翻译整句
- `沪江小D`: 备选, 解释 比 有道 完整, 可以 快速切换 语言

---

- `谷歌翻译`: 翻译专用, 建议 翻译到 英语. 
   比如 从 日本语 翻译到 简体中文 时, 谷歌会先 把 日本语 翻译成 英语,
   再把 英语 翻译成 中文, 精度会丢失. 可以试试翻译 "铭柄".
- `百度翻译`: 翻译专用, 翻译 日本语 比较准确
- `必应翻译`: 翻译专用, 备选

---

P.S.: 不支持 `海词` (https://dict.cn) 比较可惜, 不过可以用 `CNKI` 弥补一下.
