### ISSUE TITLE
关于中文版kotlin的翻译文字错误

### ISSUE THREAD

**Issue by HGXG** [hltj/kotlin-web-site-cn#224]
版本是1.4 
文档来源是位置 https://www.kotlincn.net/docs/kotlin-docs.pdf 
目录结构位置为 开始-编码规范-源文件吊称 文字错误 应为源文件名称

**Comment by hltj** [comment]
是“名”，可能pdf 显示字形有误，搜“源文件名称”能搜到的，并且我在本机打开显示的也是“源文件名称”

**Comment by liweijieok** [comment]
建议基类型翻译为父类型可能更贴切。

**Comment by hltj** [comment]
> 建议基类型翻译为父类型可能更贴切。

这块我校对的时候是按照原文对应方式，如果用 `base type` 就译为 `基类型`，如果是 `super type` 就译为 `超类型`，如果是 `parent type` 就译为 `父类型`。不过看了下可能确实有未跟原文对应的场景，有些 `super type` 翻译成了 `基类型`按说应该用 `超类型`。

**Comment by liweijieok** [comment]
在[泛型](https://www.kotlincn.net/docs/reference/generics.html) 中
```
PECS 代表生产者-Extens，消费者-Super（Producer-Extends, Consumer-Super）。
```
这一行的`Extens`应该是拼写错误，为 `Extends`

**Comment by hltj** [comment]
> 在[泛型](https://www.kotlincn.net/docs/reference/generics.html) 中
> 
> ```
> PECS 代表生产者-Extens，消费者-Super（Producer-Extends, Consumer-Super）。
> ```
> 
> 这一行的`Extens`应该是拼写错误，为 `Extends`

确实，多谢
