### ISSUE TITLE
backing field和backing property的翻译改进

### ISSUE THREAD

**Issue by ShreckYe** [hltj/kotlin-web-site-cn#228]
在现有文档中，`backing field`和`backing property`分别被翻译为`幕后字段`和`幕后属性`，即`backing`被翻译为`幕后`。而在英文中`backing`并没有`幕后`的含义，而是“支持，援助”的意思。而我认为`backing`在这里的使用，也更倾向于强调这个`backing field`或者`backing property`是在内存上存在而支持表面上可见的属性的，而不是强调这个`backing field`或者`backing property`是在幕后不可见的，因为毕竟幕后不可见的东西是很多的，比如`private`属性也可以叫做是在幕后不可见的。因此我认为，`backing`翻译为`支持`或者`支撑`是更贴近原文、更不容易造成理解歧义的选择，是更好的选择。

**Comment by hltj** [comment]
中文站最终选用 `幕后字段`/`幕后属性` 是经过探讨、深思熟虑的选择，目前在 Kotlin 社区中已广泛采用，知名的不止中文站，还有《Kotlin 核心编程》、《Kotlin 编程实践》（即将出版）等。

如果单看单个词的含义确实没有“幕后”之意，不过同样从词典来看 `backing` 不止有 `支持` 之意，还有 `衬背` 之意。再结合 `backing field/property` 的实际情况，你会发现 `支持` 表意不并不完整，其完整表意应该是**“在幕后默默提供支持的”**。
因此，译为 `幕后字段` 与 `幕后属性` 并非不妥，甚至更加合乎本意。
