### ISSUE TITLE
请问 有 关于上游 Kotlin 1.4 正式版 的 合并计划吗?

### ISSUE THREAD

**Issue by imknown** [hltj/kotlin-web-site-cn#236]
:D

**Comment by hltj** [comment]
我本地合并完毕了，正在检查行内中英文夹杂的地方，先把这些翻译下就 push 上来。

**Comment by imknown** [comment]
期待 :D

**Comment by imknown** [comment]
请问 如何修改 文档中 实例代码 使用的 `Kotlin/JVM` 编译器版本?
例如 https://www.kotlincn.net/docs/reference/classes.html#派生类初始化顺序,
不修改 `拖尾逗号` 的话, 在 `1.3.72` 已经无法编译通过了.

**Comment by hltj** [comment]
之前还真没注意，我看下

> 请问 如何修改 文档中 实例代码 使用的 `Kotlin/JVM` 编译器版本?
> 例如 [https://www.kotlincn.net/docs/reference/classes.html#派生类初始化顺序](https://www.kotlincn.net/docs/reference/classes.html#%E6%B4%BE%E7%94%9F%E7%B1%BB%E5%88%9D%E5%A7%8B%E5%8C%96%E9%A1%BA%E5%BA%8F),
> 不修改 `拖尾逗号` 的话, 在 `1.3.72` 已经无法编译通过了.

**Comment by hltj** [comment]
> 请问 如何修改 文档中 实例代码 使用的 `Kotlin/JVM` 编译器版本?
> 例如 [https://www.kotlincn.net/docs/reference/classes.html#派生类初始化顺序](https://www.kotlincn.net/docs/reference/classes.html#%E6%B4%BE%E7%94%9F%E7%B1%BB%E5%88%9D%E5%A7%8B%E5%8C%96%E9%A1%BA%E5%BA%8F),
> 不修改 `拖尾逗号` 的话, 在 `1.3.72` 已经无法编译通过了.

看了下，应该是构建环境没更新，我更新下应该重新构建一版应该就可以了

**Comment by imknown** [comment]
@hltj 已经变成 `1.4.0` 了. 😸
