### ISSUE TITLE
Kotlin Multiplatform Mobile Docs 翻译

### ISSUE THREAD

**Issue by befovy** [hltj/kotlin-web-site-cn#253]
请问 Kotlin Multiplatform Mobile Docs 的文档在此翻译计划中吗？ 希望能够参与一起翻译。

https://kotlinlang.org/lp/mobile/

https://kotlinlang.org/docs/mobile/getting-started.html

**Comment by hltj** [comment]
没找到这部分的源代码，暂时无法翻译

**Comment by befovy** [comment]
> 没找到这部分的源代码，暂时无法翻译

在这 https://github.com/JetBrains/kotlin-mobile-docs

**Comment by hltj** [comment]
我去了解下怎么整合

**Comment by imknown** [comment]
同问, 顺便还有一个 Kotlin language specification:

https://github.com/Kotlin/kotlin-spec
https://kotlinlang.org/spec/introduction.html

> This repository contains the specification of the Kotlin programming language, which describes how parts of the language should function in more detail, as compared to a more traditional user documentation on the Kotlin Website.
>
> It would be most useful to those who are interested in how Kotlin works on a finer lever and how its features interoperate, e.g., language enthusiasts, compiler writers and Kotlin power-users. However, if you are simply wondering, why some code you wrote works the way it does, this specification might help you get an answer to that.
>
> Currently, the specification covers only what we call Kotlin/Core: fundamental parts of Kotlin which should function the same way irregardless of the underlying platform. In the future, we plan to extend it with additional platform-specific sections covering Kotlin/JVM, Kotlin/JS and Kotlin/Native.
>
