### ISSUE TITLE
kotlin-web-site-cn/pages/docs/reference/ranges.md 第一个代码块代码错误

### ISSUE THREAD

**Issue by LilSacred** [hltj/kotlin-web-site-cn#258]
if (i in 1..4) {  // 等同于 1 <= i && i <= 4
    print(i)
}

这里应该是for，不是if

**Comment by hltj** [comment]
哪里得出的结论呢？kotlin 中 x in (a..b) 是一个合法布尔表达式。

官方英文也是这样写的 https://github.com/JetBrains/kotlin-web-site/blob/master/pages/docs/reference/ranges.md

**Comment by LilSacred** [comment]
我理解错了。关闭吧。抱歉。
