### ISSUE TITLE
关于kotlin反射 函数引用 属性引用 性能

### ISSUE THREAD

**Issue by rabbitmeow** [hltj/kotlin-web-site-cn#27]
反射很占用性能。我想请问一下kotlin使用函数引用或者属性引用的时候是不是很占用性能呢？还是编译器会去自动优化掉？
比如这段代码
```kotlin
(0..3).forEach(::println)
```

**Comment by hltj** [comment]
关于这个问题可以参见bennyhuo发在 Kotlin 中文博客的这篇：[Kotlin 反射有个坑你们知道么！](https://blog.kotliner.cn/2017/08/30/bug-in-kotlin-reflections/)。

p.s. 这里是中文站，内容是从官方英文中翻译过来的，需要答疑请移步到[Kotlin中文社区问答板块](https://kotliner.cn/?category=2)。
