### ISSUE TITLE
Gitbook链接失效

### ISSUE THREAD

**Issue by RoyLi-Pvt** [hltj/kotlin-web-site-cn#281]
GitBook链接现在会跳转到  
https://legacy.gitbook.com/download/epub/book/hltj/kotlin-reference-chinese  
然后跳转到首页  

![image](https://user-images.githubusercontent.com/3784599/104533785-fd797c80-564d-11eb-9f4e-b76e4d50d3c9.png)
![image](https://user-images.githubusercontent.com/3784599/104533792-01a59a00-564e-11eb-98ac-6e5b3866ba33.png)

**Comment by hltj** [comment]
嗯，已知问题。gitbook 的旧版下线了，新版不支持 include，最近有点忙一直没抽出时间来配置自己编译 gitbook，争取近期解决
