### ISSUE TITLE
plus 与 minus 操作符最后一段var和val

### ISSUE THREAD

**Issue by LonelyPluto** [hltj/kotlin-web-site-cn#286]
kotlin-web-site-cn/pages/docs/reference/collection-plus-minus.md
最后一段 “因此，它们仅在由 var 声明的只读集合中可用。 对于可变集合，如果它是一个 val，那么它们会修改集合。”
var和val是不是写反了

**Comment by hltj** [comment]
没反，官方英文就是这么写的：
``` markdown
Thus, they are available only on `var` read-only collections.
For mutable collections, they modify the collection if it's a `val`.
```
并且本来就是这个逻辑。不可变集合自身不可变，`+=`、`-=` 只能修改可变引用（var）了。`val` 引用不可变，对于可变集合就修改集合自身了。
