### ISSUE TITLE
kotlin最新版PDF使用阅读器点击目录跳转失效

### ISSUE THREAD

**Issue by jiabochao** [hltj/kotlin-web-site-cn#290]
https://book.kotlincn.net/kotlincn-docs.pdf

![image](https://user-images.githubusercontent.com/16523012/140605722-d469f28a-760c-4d5e-a606-24ce49696339.png)

**Comment by hltj** [comment]
感谢反馈，确实有这个问题，不确定是 honkit 的问题还是 calibre 的问题

我以后打算切到 mdBook，目前还在调研中

**Comment by hltj** [comment]
已修正：https://book.kotlincn.net/kotlincn-docs.pdf 。

使用 Calibre 3 构建 pdf 能够正常生成目录，但是 Calibre 3 生成的 mobi 和 epub 元信息中的书名是乱码，所以目前用两个版本构建的：
- Calibre 3 构建 pdf
- Calibre 新版构建 mobi 和 epub
