### ISSUE TITLE
希望提供最新全翻译版本

### ISSUE THREAD

**Issue by LinWanCen** [hltj/kotlin-web-site-cn#292]
官网上的版本是部分翻译的，希望有个旧版全翻译的链接

**Comment by hltj** [comment]
嗯，我也希望最新的能够完全翻译，不过未翻译的太多了，需要大家一起翻译，欢迎加入，可以参考翻译指南草稿 #35 。

旧版还在 https://www.kotlincn.net/ 还相对比较完整， www 可能会长时间停留在旧版，新版主要在 book 更新。

**Comment by LinWanCen** [comment]
其实是想有个内容旧（中的最新）但是里面的文本全翻译的链接方便大家下载，而不是内容紧跟官网最新的文档全翻译，便于推广，就像jdk api 1.6，因为其实很多新特性不一定要用上，我记得一开始学kotlin时下载的文档是全中文的。

**Comment by hltj** [comment]
应该没有你要的这种，不过有一个接近的

https://www.kotlincn.net/docs/kotlin-docs.pdf

它跟 www 一样停留在旧版（1.4.20）
