### ISSUE TITLE
浮点数的0.0与-0.0比较问题

### ISSUE THREAD

**Issue by liweijieok** [hltj/kotlin-web-site-cn#293]
我在kotlin的1.4.10的版本比较0.0与-0.0的时候，发现他们是相等的。https://www.kotlincn.net/docs/reference/basic-types.html#%E6%B5%AE%E7%82%B9%E6%95%B0%E6%AF%94%E8%BE%83

**Comment by hltj** [comment]
> 我在kotlin的1.4.10的版本比较0.0与-0.0的时候，发现他们是相等的。https://www.kotlincn.net/docs/reference/basic-types.html#%E6%B5%AE%E7%82%B9%E6%95%B0%E6%AF%94%E8%BE%83

必须的啊，这是 IEEE754 标准

文档中说的是当期静态类型不是 Double 或者 Float 的时候，比如赋值给 Comparable 时，不遵循标准
