### ISSUE TITLE
Kotlin 官⽅⽂档 中⽂版 pdf版本 目录有问题

### ISSUE THREAD

**Issue by bayesss** [hltj/kotlin-web-site-cn#294]
Kotlin 官⽅⽂档 中⽂版的目录，全部是2

**Comment by hltj** [comment]
已知问题 #290 
目前工具的问题，暂时没办法解决

**Comment by hltj** [comment]
已修正：https://book.kotlincn.net/kotlincn-docs.pdf 。

使用 Calibre 3 构建 pdf 能够正常生成目录，但是 Calibre 3 生成的 mobi 和 epub 元信息中的书名是乱码，所以目前用两个版本构建的：
- Calibre 3 构建 pdf
- Calibre 新版构建 mobi 和 epub
