### ISSUE TITLE
下载的pdf文档目录有问题

### ISSUE THREAD

**Issue by i-bugmaker** [hltj/kotlin-web-site-cn#295]
目录有问题 全部定位到了第2页

**Comment by hltj** [comment]
已知问题 #294

**Comment by hltj** [comment]
已修正：https://book.kotlincn.net/kotlincn-docs.pdf 。

使用 Calibre 3 构建 pdf 能够正常生成目录，但是 Calibre 3 生成的 mobi 和 epub 元信息中的书名是乱码，所以目前用两个版本构建的：
- Calibre 3 构建 pdf
- Calibre 新版构建 mobi 和 epub
