### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by shisheng1998** [hltj/kotlin-web-site-cn#296]
非常抱歉打扰了.

目标网页是:https://book.kotlincn.net/text/visibility-modifiers.html

在 `类成员`标题下
- `public` 移位置能见到类声明的任何客户端都可见其 public 成员。

应为
- `public` **意味着**能见到类声明的任何客户端都可见其 public 成员。

**Comment by hltj** [comment]
感谢，马上更新

**Comment by hltj** [comment]
已更新
