### ISSUE TITLE
点击下载的pdf 的目录不能跳转到对应文章内容

### ISSUE THREAD

**Issue by chrvip** [hltj/kotlin-web-site-cn#297]
点击下载的pdf 的目录不能跳转到对应文章内容

**Comment by hltj** [comment]
已知问题 #290 #294 #295 

工具的 bug，目前还没解决方案

**Comment by hltj** [comment]
已修正：https://book.kotlincn.net/kotlincn-docs.pdf 。

使用 Calibre 3 构建 pdf 能够正常生成目录，但是 Calibre 3 生成的 mobi 和 epub 元信息中的书名是乱码，所以目前用两个版本构建的：
- Calibre 3 构建 pdf
- Calibre 新版构建 mobi 和 epub
