### ISSUE TITLE
Kotlin CN有翻译组社群吗？

### ISSUE THREAD

**Issue by Smileslime47** [hltj/kotlin-web-site-cn#299]
比如说QQ群这种，因为看到好多内容都很久没更新了，感觉有一个官方的社群让译者相互沟通的话会方便很多。

**Comment by hltj** [comment]
有个QQ群，不过好久没人冒泡了😂 419484222

官方修改构建方式后停滞了一段时间，目前只能在 https://book.kotlincn.net/ 更新。
最近我个人比较忙，译者参与也少，确实更新不多。

**Comment by hltj** [comment]
p.s. 欢迎一起来翻译&维护 👏
