### ISSUE TITLE
文档注释错误

### ISSUE THREAD

**Issue by i36lib** [hltj/kotlin-web-site-cn#303]
https://book.kotlincn.net/text/idioms.html 区间迭代：
```kotlin
for (i in 1..100) { …… }  // 闭区间：包含 100
for (i in 1..< 100) { …… } // 左开右闭区间：不包含 100
for (x in 2..10 step 2) { …… }
for (x in 10 downTo 1) { …… }
(1..10).forEach { …… }
```

第二行注释错误：应该是：左闭右开区间：不包含 100

**Comment by hltj** [comment]
> https://book.kotlincn.net/text/idioms.html 区间迭代：
> 
> ```kotlin
> for (i in 1..100) { …… }  // 闭区间：包含 100
> for (i in 1..< 100) { …… } // 左开右闭区间：不包含 100
> for (x in 2..10 step 2) { …… }
> for (x in 10 downTo 1) { …… }
> (1..10).forEach { …… }
> ```
> 
> 第二行注释错误：应该是：左闭右开区间：不包含 100

确实写反了，我晚些更新

**Comment by hltj** [comment]
已更新
