### ISSUE TITLE
关于“浮点数比较”一节的翻译

### ISSUE THREAD

**Issue by msdx** [hltj/kotlin-web-site-cn#32]
地址：https://github.com/hltj/kotlin-web-site-cn/blob/master/pages/docs/reference/basic-types.md#%E6%B5%AE%E7%82%B9%E6%95%B0%E6%AF%94%E8%BE%83
原文：
>However, to support generic use cases and provide total ordering, when the operands are not statically typed as floating point numbers (e.g. Any, Comparable<...>, a type parameter), the operations use the equals and compareTo implementations for Float and Double, which disagree with the standard, so that:

译文：
>然而，为了支持泛型场景并提供全序支持，当这些操作符并非静态类型为浮点数（例如是 Any、 Comparable<……>、 类型参数）时，这些操作使用为 Float 与 Double 实现的不符合标准的 equals 与 compareTo，这会出现：

感觉读起来不大通顺，并且个别单词解释有误。
是否应该理解为：
>然而，为了支持泛型场景并提供全序支持，当这些操作符**不是**如浮点数一样的静态类型（例如是 `Any`、 `Comparable<……>`、 类型参数）时，这些操作对  `Float` 和 `Double` 使用了 `equals` 和 `compareTo` 的实现，而这与标准并不一致，因此会导致：

**Comment by hltj** [comment]
这里只有一处错别字，第一个“操作符”->“操作数”。你修改后的翻译不符合原意。
原意是如果一个动态类型是浮点数（或者说骨子里是浮点数），但字面类型（或者说看起来的的类型）是 Any 或者 Comparable<Float/Double>，这时为了支持泛型并保证全序，所使用的 equals 与 compareTo 是不满足浮点数标准的实现。比如 -0.0 < 0.0 等。

**Comment by msdx** [comment]
@hltj 谢谢，你解释得很清楚。不过原译文还是比较绕，感觉表达不是很通顺。

**Comment by hltj** [comment]
确实，如果原文能多花一些笔墨描述就好了。

**Comment by imknown** [comment]
我也觉得翻译得比较奇怪.
