### ISSUE TITLE
关于协作

### ISSUE THREAD

**Issue by imknown** [hltj/kotlin-web-site-cn#35]
~~[1.3 要正式版了...][1] 占个坑先... 方便后续讨论... (主要是 我怕我自己 忘记了...)~~

参考:
1. [开源文档翻译的质量保障实践](https://hltj.me/translate/2017/06/22/oss-docs-translate-quality.html)
1. #31 
1. #34 

[1]: https://www.kotlincn.net/docs/reference/whatsnew13.html

**Comment by hltj** [comment]
我也备注下之前整理的一些其他东西：

### 翻译的要求
- 热情与耐心
- 一定的技术基础与英文基础
- 熟悉 markdown 语法，了解 jekyll 语法
- 能够区分行文与代码：代码非注释部分保持原样，行文与代码注释部分都需要翻译
- 行文或代码注释部分一律用中文标点符号
- 英文表示并列关系的逗号，在中文中要用顿号
- 行级对照翻译，如果这导致中文从非标点符号地方断开，请使用 HTML 注释

### 一些小 tips
- `A, B, C and D` 翻译为 `甲、乙、丙与丁`
- `and` 尽量不要译为 `和`，常见译法有 `与`、`及`、`以及`、`并且`、`并`、`且`、`而`。`and other ...` 通常 `以及其他……`。`and` 有时也不译，直接逗号断句。
- `never` 有时译为 `决不` 会比 `从不` 更通顺。
- `from` 有时译为 `在……中` 比 `从……` 更好。另外也译为 `来自`、`源于`。
- `the` 有时也**要翻译**，这时翻译为 `该`、`其` 等。
- 被动语态翻译更好方式：变被动为主动、忽略主被动。
- 过去分词翻译辅助有：`已……的`、`受`、`所`。
- `while` 在子句首，可翻译为 `同时`、`而`等。
- `you`/`your`/`we`/`us` 等有时需要将对话语气转为客观描述语气。
- `specific` 指定的，具体的；`given` 给定的。
- `target` 针对，面向。
- `To do sth.` 可能表示 `要做xxx` 或者 `为做xxx`。

**Comment by hltj** [comment]
### 翻译术语表（草稿，完善中）

| 英文 | 中译 | 描述 |
|------|------|------|
| function | 函数 | 不要译作~~方法~~
| method | 方法 | 究竟译作函数还是方法，取决于原文用词
| delegate | 委托 | 不要译作~~代理~~
| proxy | 代理 | 究竟译作委托还是代理，取决于原文用词
| Range | 区间 | 与数学上的闭区间概念类似，不要翻译成~~范围~~
| Scope | 作用域 | 不要翻译成~~范围~~
| Constructor | 构造函数 | 也称构造器，不过为了统一请译为`构造函数`
| Builder | 构建器 | 不要翻译成~~构造器~~
| Kotlin Koan | Kotlin 心印 | Koan 不要翻译成~~公案~~
| Suspend Function | 挂起函数 | Suspend 本站统一称`挂起`，因此不要译为~~暂停~~
| Extension | 扩展 | 不要翻译成~~拓展~~
| Receiver | 接收者 | 词根辨析：receive 接收，accept 接受
| Target | 目标/目标平台/针对 | 当指“目标平台”时，做名词翻译为`目标平台`，做动词翻译为`针对……`或者`以……为目标平台`
| see ... for | 关于……请参见…… |
| read ... for | 关于……请参阅…… |
| refer to ... for | 关于……请参考…… |
| inference | 推断 | 不译作~~推导~~的原因是，编程语言特性“列表推导”（虽然 Kotlin 无此特性）中的“推导”对应的是 comprehension
| override | 覆盖 | 本站选用`覆盖`，因此不要译作~~重写~~
| overload | 重载 |
| backing field | 幕后字段 |
| assign(ment) | 赋值 | 通常表示赋值，不要译作分配
| reassign(ment) | 重新赋值/重复赋值 |

**Comment by imknown** [comment]
推荐一个 Microsoft 术语集, **仅供参考**:
> https://www.microsoft.com/zh-cn/language

**Comment by hltj** [comment]
> 推荐一个 Microsoft 术语集, **仅供参考**:
> 
> > https://www.microsoft.com/zh-cn/language

手欠搜了个协程 😂

**Comment by imknown** [comment]
@hltj `coroutine` 翻译成 `协同程序` 和 `协同例程` 啦, 估计是 `协程` 的 全称吧. 维基百科搜 `协同程序` 也会跳转到 `协程`... 好不统一...

**Comment by hltj** [comment]
@imknown 嗯，微软大多数翻译的挺好的，只有个别的有些问题

**Comment by imknown** [comment]
@hltj 分享一个 微软翻译的 新闻 https://www.ithome.com/0/395/344.htm 🤣

**Comment by hltj** [comment]
> @hltj 分享一个 微软翻译的 新闻 https://m.ithome.com/html/395344.htm 🤣

我之前看过，不过必应的翻译还是不行，没有谷歌的好，也没有搜狗的好

**Comment by Shadowell** [comment]
有没有认领任务表？任务如何分配？如何协作？

**Comment by hltj** [comment]
> 有没有认领任务表？任务如何分配？如何协作？

目前没有按照任务领取方式，主要是考虑两点：
1) 《对于初次翻译的要求》中也有提到，不鼓励一次翻译过多的内容，不便于 review、校对。而如果一次翻译内容不多的话，不按照领取方式也不会有太多重复劳动的浪费。
2) 避免领取任务长期不能完成，而其他人不便参与。基于这一点，建议不只初翻，其他情况也都按照小步快走方式。

这里协作主要指不同人翻译如何保持一贯风格，以及 review、校对别人翻译时的参考。

**Comment by imknown** [comment]
https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN#fuchsia-os-中文社区简体中文文档
看到了这个, 链接备份一下.

**Comment by panda8z** [comment]
> > 有没有认领任务表？任务如何分配？如何协作？
> 
> 目前没有按照任务领取方式，主要是考虑两点：
> 
> 1. 《对于初次翻译的要求》中也有提到，不鼓励一次翻译过多的内容，不便于 review、校对。而如果一次翻译内容不多的话，不按照领取方式也不会有太多重复劳动的浪费。
> 2. 避免领取任务长期不能完成，而其他人不便参与。基于这一点，建议不只初翻，其他情况也都按照小步快走方式。
> 
> 这里协作主要指不同人翻译如何保持一贯风格，以及 review、校对别人翻译时的参考。

好的。目前我正在参与翻译Flutter文档，我们这个Kotlin文档没有具体的Wiki指明该如何提交翻译的代码

**Comment by hltj** [comment]
> > > 有没有认领任务表？任务如何分配？如何协作？
> > 
> > 
> > 目前没有按照任务领取方式，主要是考虑两点：
> > 
> > 1. 《对于初次翻译的要求》中也有提到，不鼓励一次翻译过多的内容，不便于 review、校对。而如果一次翻译内容不多的话，不按照领取方式也不会有太多重复劳动的浪费。
> > 2. 避免领取任务长期不能完成，而其他人不便参与。基于这一点，建议不只初翻，其他情况也都按照小步快走方式。
> > 
> > 这里协作主要指不同人翻译如何保持一贯风格，以及 review、校对别人翻译时的参考。
> 
> 好的。目前我正在参与翻译Flutter文档，我们这个Kotlin文档没有具体的Wiki指明该如何提交翻译的代码

选择未翻译的文档（也可以直接在 Kotlin 中文站文档右上角的编辑本页通过 github 在线编辑，不过不建议）直接翻译一段，然后提 PR 就好。不建议一次翻译过多内容。另外这个 issue 全部内容相当于翻译指南，需要在翻译前阅读。

**Comment by Baojintong** [comment]
还不如英文的好理解。

**Comment by cpdyj** [comment]
额为什么 artifact 这种词汇也要翻译呢，实际使用中出现中文的地方少之又少吧（x

**Comment by hltj** [comment]
> 额为什么 artifact 这种词汇也要翻译呢，实际使用中出现中文的地方少之又少吧（x

可能习惯不一样，我是综合了身边人和读过的一些书，来取的“构件”

**Comment by HoshinoTented** [comment]
从最近的翻译工作中有一些小建议：
build、compilation、dependeny 之类的 **名词** 应翻译为：构建**项**、编译**项** 与 依赖**项**。
但是过去的翻译中有的仅仅翻译为：构建、编译、依赖 ~~（说的就是我）~~ 。
不知道能否统一一下？

**Comment by HoshinoTented** [comment]
还有个问题，`variants` 一般要翻译成什么？

**Comment by hltj** [comment]
> 从最近的翻译工作中有一些小建议：
> build、compilation、dependency 之类的 **名词** 应翻译为：构建**项**、编译**项** 与 依赖**项**。
> 但是过去的翻译中有的仅仅翻译为：构建、编译、依赖 ~（说的就是我）~ 。
> 不知道能否统一一下？

赞同，我加到术语表里。
只是 build 可能还表示“构建过程”，可以具体看，我回头也改改之前翻译不到位的地方。

**Comment by HoshinoTented** [comment]
> > 从最近的翻译工作中有一些小建议：
> > build、compilation、dependency 之类的 **名词** 应翻译为：构建**项**、编译**项** 与 依赖**项**。
> > 但是过去的翻译中有的仅仅翻译为：构建、编译、依赖 ~（说的就是我）~ 。
> > 不知道能否统一一下？
> 
> 赞同，我加到术语表里。
> 只是 build 可能还表示“构建过程”，可以具体看，我回头也改改之前翻译不到位的地方。

好的，了解了

**Comment by hltj** [comment]
> 还有个问题，`variants` 一般要翻译成什么？

Android 的构建变体，它的文档中文版就是这么写的
https://developer.android.com/studio/build/build-variants.html

**Comment by ShreckYe** [comment]
作为一个新的贡献者，我想对术语表提出一些补充，这些是我不确定怎么翻译又没有在术语表中看到的，通过对照其他翻译才确定的：
# 不翻译术语表

英文 | 描述
-- | --
getter/setter |

# 翻译术语表
英文 | 中译 | 描述
-- | -- | --
qualifier | 限定符 |
for example | 例如 | 不要译作~比如~

**Comment by hltj** [comment]
> 作为一个新的贡献者，我想对术语表提出一些补充，这些是我不确定怎么翻译又没有在术语表中看到的，通过对照其他翻译才确定的：
> 
> ### 不翻译术语表
> 英文	描述
> getter/setter	
> ### 翻译术语表
> 英文	中译	描述
> qualifier	限定符	
> for example	例如	不要译作~比如~

赞同这样取舍，我加进术语表里，我打算以后单开一个类似于翻译指南的项目，这样就方便大家一起维护术语表了

**Comment by imknown** [comment]
今天看 https://s.android.com/devices/architecture/modular-system/sdk-extension?hl=zh-cn, 
发现站内已经启用了 [Cloud Translation API](https://cloud.google.com/translate/?hl=zh-cn) 功能. 翻译得一般, 先备注下.

**Comment by 2BAB** [comment]
陆续补一下翻 KMM 文档过程中的词汇表：

| 英文        | 中译           | 描述  |
| ------------- |:-------------:| -----:|
| workaround      | 变通方案 | 形容因为某些原因目前无法优雅解决，所以采用变通的绕过去的方案 |
| Kotlin Multiplatform Mobile(KMM)| Kotlin 移动多平台（KMM）| 建议都加上（KMM）的注释加快中文理解|
